<?php
declare(strict_types=1);
final class FileService {
    private const ALLOWED=['application/pdf'=>'pdf','image/jpeg'=>'jpg','image/png'=>'png','application/vnd.openxmlformats-officedocument.wordprocessingml.document'=>'docx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'=>'xlsx'];
    public static function uploadDocument(int $documentId,array $file,string $role='attachment'): array {
        $d=DocumentService::find($documentId);RbacService::authorize('documents.update',(int)$d['owner_unit_id']);if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('Upload gagal.',422);if((int)$file['size']>20*1024*1024)throw new RuntimeException('Ukuran maksimum 20 MB.',422);
        $mime=(new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);if(!isset(self::ALLOWED[$mime]))throw new RuntimeException('Jenis file tidak diizinkan.',422);$ext=self::ALLOWED[$mime];$name=bin2hex(random_bytes(20)).'.'.$ext;$dir=dirname(__DIR__,2).'/storage/private/documents/'.$documentId;if(!is_dir($dir))mkdir($dir,0770,true);$path=$dir.'/'.$name;if(!move_uploaded_file($file['tmp_name'],$path))throw new RuntimeException('File tidak dapat disimpan.',500);$hash=hash_file('sha256',$path);$u=AuthService::requireUser();$q=Database::connection()->prepare('INSERT INTO document_files(document_id,document_version_id,uploaded_by,file_role,original_name,storage_path,mime_type,extension,file_size,checksum_sha256) VALUES(?,?,?,?,?,?,?,?,?,?)');$q->execute([$documentId,null,$u['id'],$role,basename($file['name']),$path,$mime,$ext,$file['size'],$hash]);$id=(int)Database::connection()->lastInsertId();AuditService::log('file.uploaded','document_file',$id,null,['document_id'=>$documentId,'hash'=>$hash]);return ['id'=>$id,'name'=>basename($file['name']),'mime'=>$mime,'size'=>(int)$file['size'],'checksum'=>$hash];
    }
    public static function download(int $id): never {$u=AuthService::requireUser();$q=Database::connection()->prepare('SELECT f.*,d.owner_unit_id FROM document_files f JOIN documents d ON d.id=f.document_id WHERE f.id=? AND f.deleted_at IS NULL');$q->execute([$id]);$f=$q->fetch();if(!$f)throw new RuntimeException('File tidak ditemukan.',404);RbacService::authorize('documents.view',(int)$f['owner_unit_id']);if(!is_file($f['storage_path'])||!hash_equals($f['checksum_sha256'],hash_file('sha256',$f['storage_path'])))throw new RuntimeException('Integritas file gagal diverifikasi.',409);AuditService::log('file.downloaded','document_file',$id);header('Content-Type: '.$f['mime_type']);header('Content-Disposition: attachment; filename="'.rawurlencode($f['original_name']).'"');header('Content-Length: '.$f['file_size']);header('X-Content-Type-Options: nosniff');readfile($f['storage_path']);exit;}
}
