<?php
declare(strict_types=1);
final class WorkflowService {
    public static function submit(int $documentId): array {
        $d=DocumentService::find($documentId);RbacService::authorize('documents.submit',(int)$d['owner_unit_id']);if(!in_array($d['status'],['draft','revision'],true))throw new RuntimeException('Status dokumen tidak dapat diajukan.',409);
        return Database::transaction(function(PDO $db)use($d,$documentId){$q=$db->prepare('SELECT * FROM workflow_definitions WHERE institution_id=? AND document_type_id=? AND (unit_id=? OR unit_id IS NULL) AND is_active=1 ORDER BY unit_id DESC,version_no DESC LIMIT 1');$q->execute([$d['institution_id'],$d['document_type_id'],$d['owner_unit_id']]);$def=$q->fetch();if(!$def)throw new RuntimeException('Alur persetujuan belum dikonfigurasi.',422);
            $db->prepare('INSERT INTO workflow_instances(document_id,workflow_definition_id,definition_snapshot,status,current_step_no,started_at) VALUES(?,?,?,"running",1,NOW())')->execute([$documentId,$def['id'],json_encode($def)]);$instance=(int)$db->lastInsertId();$steps=$db->prepare('SELECT * FROM workflow_definition_steps WHERE workflow_definition_id=? ORDER BY step_no');$steps->execute([$def['id']]);
            foreach($steps as $s){$status=(int)$s['step_no']===1?'active':'waiting';$due=$s['sla_minutes']?date('Y-m-d H:i:s',time()+((int)$s['sla_minutes']*60)):null;$db->prepare('INSERT INTO workflow_steps(workflow_instance_id,definition_step_id,step_no,name,action_type,execution_mode,minimum_approvals,status,sla_due_at,activated_at) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$instance,$s['id'],$s['step_no'],$s['name'],$s['action_type'],$s['execution_mode'],$s['minimum_approvals'],$status,$due,$status==='active'?date('Y-m-d H:i:s'):null]);$stepId=(int)$db->lastInsertId();if($status==='active')self::assignActors($db,$stepId,$s,$d);}
            $db->prepare('UPDATE documents SET status="under_review",submitted_at=NOW() WHERE id=?')->execute([$documentId]);AuditService::log('document.submitted','document',$documentId);return DocumentService::find($documentId);
        });
    }
    private static function assignActors(PDO $db,int $stepId,array $s,array $d): void {$sql='SELECT DISTINCT ur.user_id FROM user_roles ur';$params=[];if($s['approver_type']==='role'){$sql.=' WHERE ur.role_id=? AND ur.institution_id=? AND (ur.unit_id IS NULL OR ur.unit_id=?)';$params=[$s['approver_reference_id'],$d['institution_id'],$d['owner_unit_id']];}else{$sql.=' WHERE ur.institution_id=? AND (ur.unit_id IS NULL OR ur.unit_id=?) LIMIT 1';$params=[$d['institution_id'],$d['owner_unit_id']];}$q=$db->prepare($sql);$q->execute($params);foreach($q->fetchAll() as $a){$db->prepare('INSERT IGNORE INTO workflow_step_actors(workflow_step_id,user_id) VALUES(?,?)')->execute([$stepId,$a['user_id']]);NotificationService::send((int)$a['user_id'],'approval-'.$stepId,'approval','Dokumen menunggu persetujuan',$d['title'],'document',(int)$d['id'],'?page=approvals');}}
    public static function decide(int $stepId,string $decision,?string $notes=null): void {if(!in_array($decision,['approved','revision','rejected'],true))throw new InvalidArgumentException('Keputusan tidak valid.');RbacService::authorize('approvals.decide');$u=AuthService::requireUser();
        Database::transaction(function(PDO $db)use($stepId,$decision,$notes,$u){$q=$db->prepare('SELECT ws.*,wi.document_id,d.current_version_no,d.institution_id,d.owner_unit_id,d.numbering_scheme_id,d.creator_id,d.title FROM workflow_steps ws JOIN workflow_instances wi ON wi.id=ws.workflow_instance_id JOIN documents d ON d.id=wi.document_id JOIN workflow_step_actors a ON a.workflow_step_id=ws.id AND a.user_id=? WHERE ws.id=? AND ws.status="active" FOR UPDATE');$q->execute([$u['id'],$stepId]);$s=$q->fetch();if(!$s)throw new RuntimeException('Tahap tidak tersedia untuk Anda.',403);if(in_array($decision,['revision','rejected'])&&!trim((string)$notes))throw new InvalidArgumentException('Catatan wajib diisi.');
            $db->prepare('INSERT INTO approvals(workflow_step_id,actor_id,decision,notes,ip_address,user_agent,version_no_reviewed) VALUES(?,?,?,?,?,?,?)')->execute([$stepId,$u['id'],$decision,$notes,Security::clientIp(),substr($_SERVER['HTTP_USER_AGENT']??'',0,500),$s['current_version_no']]);$db->prepare('UPDATE workflow_step_actors SET status="acted" WHERE workflow_step_id=? AND user_id=?')->execute([$stepId,$u['id']]);
            if($decision!=='approved'){$status=$decision==='revision'?'revision':'rejected';$db->prepare('UPDATE workflow_steps SET status=?,completed_at=NOW() WHERE id=?')->execute([$status,$stepId]);$db->prepare('UPDATE workflow_instances SET status=?,completed_at=NOW() WHERE id=?')->execute([$status==='revision'?'cancelled':'rejected',$s['workflow_instance_id']]);$db->prepare('UPDATE documents SET status=? WHERE id=?')->execute([$status,$s['document_id']]);NotificationService::send((int)$s['creator_id'],$decision.'-'.$stepId,'workflow','Dokumen '.$status,$s['title'],'document',(int)$s['document_id'],'?page=document-detail&id='.$s['document_id']);}
            else{$count=$db->prepare("SELECT COUNT(*) FROM approvals WHERE workflow_step_id=? AND decision='approved'");$count->execute([$stepId]);if((int)$count->fetchColumn()>=(int)$s['minimum_approvals']){$db->prepare('UPDATE workflow_steps SET status="approved",completed_at=NOW() WHERE id=?')->execute([$stepId]);$next=$db->prepare('SELECT * FROM workflow_steps WHERE workflow_instance_id=? AND step_no>? ORDER BY step_no LIMIT 1');$next->execute([$s['workflow_instance_id'],$s['step_no']]);$n=$next->fetch();if($n){$db->prepare('UPDATE workflow_steps SET status="active",activated_at=NOW() WHERE id=?')->execute([$n['id']]);$def=$db->prepare('SELECT * FROM workflow_definition_steps WHERE id=?');$def->execute([$n['definition_step_id']]);self::assignActors($db,(int)$n['id'],$def->fetch(),$s);}else{if($s['numbering_scheme_id'])NumberingService::assign($db,(int)$s['document_id']);$db->prepare('UPDATE workflow_instances SET status="approved",completed_at=NOW() WHERE id=?')->execute([$s['workflow_instance_id']]);$db->prepare('UPDATE documents SET status="approved",approved_at=NOW() WHERE id=?')->execute([$s['document_id']]);}}}
            AuditService::log('workflow.'.$decision,'document',(int)$s['document_id'],null,['step_id'=>$stepId,'notes'=>$notes]);
        });
    }
}
