<?php $hour=(int)date('H'); $greeting=$hour<11?'Selamat pagi':($hour<15?'Selamat siang':($hour<18?'Selamat sore':'Selamat malam')); ?>
<div class="page-shell">
 <header class="page-header"><div><p class="eyebrow">SIMANTAP / RUANG KERJA</p><h1>Dashboard<span>.</span></h1><p>Pantau surat, persetujuan, penugasan, dan laporan dalam satu ruang kerja.</p></div><div class="date-chip"><i class="ri-calendar-2-line"></i><?= date('d/m/Y') ?></div></header>
 <section class="welcome"><div><span class="welcome-kicker"><i></i> SELAMAT DATANG KEMBALI</span><h2><?= $greeting ?>, <?= e(explode(' ', $user['name'] ?? 'Pengguna')[0]) ?>.</h2><p>Assalamu’alaikum. Ada <?= count($approvals) ?> dokumen yang membutuhkan perhatian Anda hari ini.</p><a class="welcome-button" href="?page=approvals">Periksa persetujuan <i class="ri-arrow-right-line"></i></a></div><div class="system-badge"><span><i class="ri-shield-check-line"></i></span><div><small>STATUS SISTEM</small><strong>Portal siap & aktif</strong><em>Semua layanan normal</em></div></div></section>
 <nav class="quick-links"><span>AKSES CEPAT</span><a href="?page=create-document"><i class="ri-file-add-line"></i>Buat surat</a><a href="?page=approvals"><i class="ri-file-check-line"></i>Persetujuan</a><a href="?page=agenda"><i class="ri-calendar-event-line"></i>Agenda</a><a href="?page=archive"><i class="ri-archive-line"></i>Cari arsip</a></nav>
 <div class="metric-grid">
  <a class="metric-card blue" href="?page=documents"><div><span class="metric-icon"><i class="ri-file-list-3-line"></i></span><i class="ri-arrow-right-up-line arrow"></i></div><small>TOTAL SURAT</small><strong><?= count($documents) ?></strong><p>Semua draf & surat resmi</p></a>
  <a class="metric-card amber" href="?page=approvals"><div><span class="metric-icon"><i class="ri-time-line"></i></span><i class="ri-arrow-right-up-line arrow"></i></div><small>MENUNGGU PERSETUJUAN</small><strong><?= count($approvals) ?></strong><p>Dokumen butuh tindakan</p></a>
  <a class="metric-card violet" href="?page=assignments"><div><span class="metric-icon"><i class="ri-briefcase-4-line"></i></span><i class="ri-arrow-right-up-line arrow"></i></div><small>PENUGASAN SAYA</small><strong><?= count($assignments) ?></strong><p>Surat tugas aktif</p></a>
  <a class="metric-card teal" href="?page=reports"><div><span class="metric-icon"><i class="ri-checkbox-circle-line"></i></span><i class="ri-arrow-right-up-line arrow"></i></div><small>LAPORAN AKTIF</small><strong><?= count(array_filter($assignments, fn($a) => ($a['status'] ?? '') !== 'Selesai')) ?></strong><p>Belum selesai</p></a>
 </div>
 <div class="dashboard-grid">
  <section class="panel span-2"><div class="panel-head"><div><h2>Surat terbaru</h2><p>Perkembangan dokumen lintas unit</p></div><a href="?page=documents">Lihat semua <i class="ri-arrow-right-line"></i></a></div><div class="document-list"><?php foreach(array_slice($documents,0,4) as $doc): ?><a class="document-row" href="?page=document-detail&id=<?= $doc['id'] ?>"><span class="doc-icon <?= status_class($doc['status']) ?>"><i class="ri-file-text-line"></i></span><div class="doc-main"><strong><?= e($doc['title']) ?></strong><small><?= e($doc['number']) ?> · <?= e($doc['unit']) ?></small></div><span class="status-chip <?= status_class($doc['status']) ?>"><?= e($doc['status']) ?></span><time><?= format_date_id($doc['date']) ?></time><i class="ri-arrow-right-s-line row-arrow"></i></a><?php endforeach; ?></div></section>
  <section class="panel"><div class="panel-head"><div><h2>Agenda terdekat</h2><p>Kegiatan 7 hari ke depan</p></div><a href="?page=agenda">Kalender</a></div><div class="agenda-list"><div class="agenda-item"><div class="agenda-date"><strong>16</strong><span>SEP</span></div><div><strong>Pendampingan Akreditasi</strong><p><i class="ri-time-line"></i> 08.00–12.00 · Ruang Fakultas</p></div></div><div class="agenda-item"><div class="agenda-date violet"><strong>18</strong><span>SEP</span></div><div><strong>Audit Infrastruktur TI</strong><p><i class="ri-time-line"></i> 09.00–15.00 · Gedung Terpadu</p></div></div><div class="agenda-item"><div class="agenda-date teal"><strong>22</strong><span>SEP</span></div><div><strong>Rapat Koordinasi Pimpinan</strong><p><i class="ri-time-line"></i> 13.00–15.00 · Ruang Senat</p></div></div></div></section>
 </div>
</div>
